name: default

steps:
  - name: Plan
    executor: api
    model: $planner
    prompt_template: plan
    input: [TICKET.md, project:context]
    output: PLAN.md

  - name: Review
    executor: api
    model: $reviewer
    prompt_template: review
    input: [PLAN.md]
    output: REVIEW.md

  - name: Revise
    executor: api
    model: $editor
    prompt_template: revise
    input: [PLAN.md, REVIEW.md, project:context]
    output: PLAN.md
