name: default

steps:
  - name: Plan
    executor: api
    model: anthropic/claude-opus-4-6
    prompt_template: plan
    input: [TICKET.md]
    output: PLAN.md

  - name: Review
    executor: api
    model: moonshotai/kimi-k2.5
    prompt_template: review
    input: [PLAN.md]
    output: REVIEW.md

  - name: Revise
    executor: api
    model: anthropic/claude-sonnet-4-6
    prompt_template: revise
    input: [PLAN.md, REVIEW.md]
    output: PLAN.md

  - name: Implement
    executor: claude-code
    input: [PLAN.md]

  - name: Test
    executor: shell
    command: "go test ./..."
    output: TEST.md

  - name: Audit
    executor: api
    model: openai/codex-5.3
    prompt_template: code-review
    input: [PLAN.md, "git:diff"]
    output: REVIEW-CODE.md

  - name: Fix
    executor: claude-code
    input: [REVIEW-CODE.md]

  - name: PR
    type: github-pr
    title_from: TICKET.md
    body_template: pr-summary
